### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by jsayles** [Cobuilding/cobuilding.ca#12]
We need a way to see how much traffic we are getting.  Generally I've used google analytics although I'd be excited to find a good, open alternative.  @bmann got any tricks up your sleeve?

**Comment by bmann** [comment]
Lots. Why do we need to know how much traffic we are getting?

What actions will we take if there is more or less traffic in a week?

Don’t we mostly just want to know how many people take an action, like subscribing to a newsletter or filling out a survey?

Post Hog is open source with a free tier on their cloud platform.

**Comment by jsayles** [comment]
Always a good question to start with.  Key reasons I want analytics is to notice I there are any unusual spikes.  Not for action, but for understanding.  If someone ends up linking to us it is valuable for us to discover that and reach out.

**Comment by jsayles** [comment]
Since we already decided we can't escape the google I set up a google analytics account.
