### ISSUE TITLE
Move to vancouver.cobuilding.ca

### ISSUE THREAD

**Issue by jsayles** [Cobuilding/cobuilding.ca#7]
I'd like the site to be more location specific and I think we can do that by making the main domain vancouver.cobuilding.com.  I'd then like to setup a redirect at cobuilding.ca to go to this new domain.  That way we don't have to explain the full path every time we give the URL out.  

@bmann I believe this is all you as you control the DNS.  Let me know if I can help or if you object to this line of thinking.

**Comment by bmann** [comment]
You have access to the DNS, too.

I don't think we should do this. Most of the issues are Canada wide (as in, not even just scoped to BC). "Cobuying with friends" is relevant everywhere.

We will mostly have Vancouver / BC centric content right now. Needing to make it easy to find just the Vancouver stuff is a) either a future us problem, when there is content from all over) or b) solved by making a top level /vancouver/ page that filters everything tagged with Vancouver.

Or even to be more specific could be CoV. Or GVRD? Or Islands???

**Comment by jsayles** [comment]
This is a good discussion so I am glad for the moment I have forgotten how we handle DNS.  We can get back to that when we  come up with a decision on this issue.

I'm still feeling like we should do this, if only for now.  I agree with you that housing does have a wider scope but if we set our scope too wide on this project we dilute our efforts locally.  We are already rather diluted with the broad/generic moniker of "cobuilding" on the broad topic of "housing".  

I'd much rather have a future problem of expanding vancouver.cobuilding.ca to be nation wide than fight every day (starting now) to explain exactly how this site is relevant to any individual we talk to.  That is why I am trying to hone the scope down to building+housing+vancouver.

**Comment by jsayles** [comment]
Talked it through and the plan moving forward is to keep with the copy changes "Cobuilding in Vancouver" and such but leave the domain as cobuilding.ca.
